version: "3"

services:
  bc-nginx:
    image: nginx
    container_name: bc-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  bc-front:
    build: ./frontend/
    container_name: bc-front
  bc-back:
    build: ./backend/
    container_name: bc-back

